config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :creatures

  resources :tags

end

app/models/creature.rb
class Creature < ActiveRecord::Base
  has_and_belongs_to_many :tags
end

app/models/creatures_tags.rb
class CreaturesTags < ActiveRecord::Base
  belongs_to :creature
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :creatures
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/creatures_controller.rb
class CreaturesController < ApplicationController

  def index
    @creatures = Creature.all
  end

  def show
    @creature = Creature.find(params[:id])
    @tags = @creature.tags
  end

  def new # displays the form new record
    @creature = Creature.new
    @tags = Tag.all
  end

  def create # save new record
    @creature = Creature.new(creature_params) #Creature.create(creature_params) will also work withouth having to add Creature.save on the next line. This will create it and save it in one step
    @creature.save
    # update_tags c
    redirect_to creatures_path
  end



  def edit #display form for existing
    @creature = Creature.find(params[:id])
    @tags = Tag.all
  end

  def update
    # render json: params
    c = Creature.find params[:id]
    c.update creature_params

    c.tags.clear
    update_tags c

    redirect_to creatures_path
  end

  def destroy
    Creature.find(params[:id]).delete
    redirect_to creatures_path
  end

  private

  def update_tags creature
    creature_tags = params[:creature][:tag_ids]
    creature_tags.each do |id|
      creature.tags << Tag.find(id) unless id.blank?
    end
  end

  def creature_params
    params.require(:creature).permit(:description,:name)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @creature = Creature.all
     @tags = Tag.select("tags.*,count(creatures.id) AS creature_count").joins(:creatures).group("tags.id").order("creature_count DESC").limit(15)
     @tags.to_a.shuffle!
     #Tag.all
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end

  def new
  end

  def show
    @tag = Tag.find params[:id]
  end

  def destroy
    Tag.find(params[:id]).delete
    redirect_to tags_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/creatures_helper.rb
module CreaturesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/creatures/_form.html.erb
<h3>Create a Creature</h3>

<%= bootstrap_form_for @creature do |c| %>
  <%= c.text_field :name %>
  <%= c.text_area :description %>

  <%= c.collection_check_boxes :tag_ids, @tags, :id, :name %>

  <%= c.primary %>
<% end %>

app/views/creatures/edit.html.erb
<%= render partial: 'form' %>

app/views/creatures/index.html.erb
<div class="col-xs-4 col-sm-6 col-md-8 col-lg-12">
<%= link_to "", new_creature_path, class: 'btn btn-primary btn-xs glyphicon glyphicon-plus pull-right' %>
<h1>Bog creatures</h1>


  <% @creatures.each do |creature| %>
    <div class="well">
    <p class="creatures">Name: <%= creature.name %></p>
    <p>Description: <%= creature.description %></p>

    <%= link_to "Show", creature, :class=>"btn btn-primary btn-xs" %>
    <%= link_to " Edit", edit_creature_path(creature), class: 'btn btn-primary btn-xs glyphicon glyphicon-pencil pull-right' %>
    <%= link_to " Destroy", creature, method: :delete, class: 'btn btn-danger btn-xs glyphicon glyphicon-trash pull-right', data: { confirm: 'Are you sure?' } %>
    <p>
      <% creature.tags.each do |tag| %>
      <%= link_to "##{tag.name}", tag %>
      <% end %>
    </p>
  </div>
  <% end %>

</div>

app/views/creatures/new.html.erb
<%= render partial: 'form' %>

app/views/creatures/show.html.erb
<h3>
  CREATURE
</h3>

<%= link_to "&larr; back".html_safe, creatures_path, :class=>"btn btn-primary btn-xs back" %>
<%= link_to "", new_creature_path, class: 'btn btn-primary btn-xs glyphicon glyphicon-plus pull-right' %>

  <div class="well">
    <p><span class = "creatures">
      Name: <%= @creature.name %></span> |
      Posted At:  <%= @creature.created_at%>
    </p>
    <p>Description: <%= @creature.description %></p>
    <div>
        <h5>Tags</h5>
          <ul>
          <% @tags.each do |tag| %>
            <li><%= tag.name %></li>
          <% end %>
          </ul>
        </div>


  </div>

app/views/creatures/tag.html.erb
<div class="row">
<div class="col-md-7 col-md-offset-1">
<%= render 'form' %>
<h1>View Creatures by Tag: <small><%= params[:tag] %> </small></h1>

  <div><%= link_to "&larr; back to list".html_safe, creatures_path %></div><br/>


<div class="row">

  <div class="col-sm-8">
<div class="tags">

          <h3>Skye Bog Creatures Tagged: <%= params[:tag] %></h3>


        <% @creature.each do |creature| %>
          <td><%= creature.name %></td><br/>


      <% end %>

    </div>
    </div>
  </div> <!-- close div row-->
  </div>
  </div><!-- close main div row -->

app/views/home/index.html.erb
<div class = "container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <h1></h1>


    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bog Creatures Lab</title>
  <link rel="stylesheet" media="screen" href="//netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <script src="//code.jquery.com/jquery.js"></script>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<div class="container">
  <div class="row">


    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <div class="page-header">
        <h1>Bog Creatures</h1>
    </div>
      <ul class="nav nav-pills nav_bar">
        <li role="presentation" class="active"><%= link_to 'Home', '/' %></li>
        <li role="presentation"><%= link_to 'Creatures', creatures_path %></li>
        <li role="presentation"><%= link_to 'New Creature',new_creature_path %></li>
      </ul>
    </div>
    <div class="col-xs-4 col-sm-6 col-md-8 col-offset-2">

      <div class="well">
        <p>When I think of Bog creatures, it makes me think of the Diablo game from Blizzard. Bog Creatures are Frog Demons which live in the jungles of Kehjistan. This amphibian beasts can be encountered usually near creeks, where they emerge and might take a careless hero by surprise. Bog Creatures have a harmless melee attack. However they shoot much more effective fire balls from distance that have a knockback effect. I have included a few of them. If you happen to know a few more, please make sure to add them to the list.</p>
      </div>
    </div>

  </div>
  <div class="row">
    <div class="col-xs-8 col-sm-8 col-md-8 col-lg-8">
      <%= yield %>
    </div>

  </div>
</div>

</body>
</html>

app/views/tags/index.html.erb
<h1>Tags</h1>



<% @tags.each do |tag| %>
<div class="well">
  <h2>#<%= link_to tag.name, tag %></h2>
</div>
<% end %><h1>Tags#index</h1>
<p>Find me in app/views/tags/index.html.erb</p>

app/views/tags/show.html.erb
<h2>#<%= @tag.name %><%= link_to " Destroy", @tag, method: :delete, class: 'btn btn-danger btn-xs glyphicon glyphicon-trash pull-right', data: { confirm: 'Are you sure?' } %></h2>

<% @tag.creatures.each do |creature| %>
<div class="well">
  <%= link_to creature.name, creature %>
</div>
<% end %>